baseURL = "https://your-site.netlify.app/"
title = "My Auto Blog"
paginate = 12

# Enable unsafe HTML rendering (needed for shortcodes/ads)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Theme via Hugo Modules
[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[params]
  description = "Automated blog powered by Hugo, Netlify, and GitHub Actions"
  author = "Your Name"

# Default taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
